### ISSUE TITLE
Doesn't protect against url params

### ISSUE THREAD

**Issue by jdcrecur** [efkan/content-filter#1]
Can this module somehow protect against params?

```
app.get('/api/details-fetch/:_id', authenticated.yes, function(req, res) {
      var id = req.params._id   //  <-- how to auto protect against #injection here?
})
```

**Comment by efkan** [comment]
I think you've figured out how content-filter works. Good luck.

Although that, I am writing because of somebody else may ask the same question.
Content-filter checks the `req.originalUrl` value that includes `req.query` parameters for a GET method.

**Comment by jdcrecur** [comment]
Awesome thanks. Cool module btw thanks for writing!

**Comment by efkan** [comment]
Hello @johnc1984 ,

`content-filter` has been updated for ability to work on static html pages. I would recommend getting new updates.
Writing convenient command `npm i content-filter --save` to copy-paste purpose of a better service :)
