### ISSUE TITLE
Injection via headers (especially cookies)

### ISSUE THREAD

**Issue by T-vK** [efkan/content-filter#4]
Let's say you have a sessionId stored in a cookie.  
To check if the id is valid, you will probably make a db query, right? 
So that might be a serious weak spot. I think all headers, or at least some should be filtered, too.

**Comment by efkan** [comment]
Thank you for sharing your thoughts.

For now it seems good for now. 

[Express-session](https://github.com/expressjs/session/blob/1940ce9abc00e123967c2b11c4426da48c3681c9/README.md#secret) provides a secret key option to [sign](https://github.com/expressjs/session/blob/d95275bd5345b161585ec7c6de22bcd77b484a65/index.js#L606) and to [unsign](https://github.com/expressjs/session/blob/d95275bd5345b161585ec7c6de22bcd77b484a65/index.js#L629) sessionId.

I'm closing the issue. If you have another thought about security, feel free to write again.
