### ISSUE TITLE
Call error middleware instead send response

### ISSUE THREAD

**Issue by netpedro-com** [efkan/content-filter#6]
Please, create a `var error = new Error('Message error.'); error.status = 403` and pass to `next(error)` and let the developer choose what to do. BTW, nice package :)

**Comment by efkan** [comment]
`dispatchToErrorHandler` option was added.

Please find the related part in the [guide](https://github.com/efkan/content-filter/blob/master/README.md#guide) of `content-filter`.

Enjoy! :smiley:
