### ISSUE TITLE
How can I check only `req.body` properties names?

### ISSUE THREAD

**Issue by netpedro-com** [efkan/content-filter#7]
Sorry, I just delve into source code and couldn't find out I way to check only for properties names `_id`, `$ne`, `count` in this `req.body`:

```json
{
    _id: { $ne: "abcd" },
    count: 10
}
```
I tried `typeList: ['object', 'function']` but not works. From my point of view, `"abcd"` and `10` should not be include by default. Would be nice to create an option `checkOnlyNames`.

Please, someone could help me. Thanks in advance.

**Edited**: After delve into source code, now I understand the purpose of this package (content-filter). The primary purpose is to check **form data** or **the user input**. What I want is only sanitize object properties names. So I think this package isn't for my needs. Isn't?

**Comment by efkan** [comment]
Hello Pedro,

These days I' really too busy to handle this job.

However if you want to contribute with a `Pull Request`, it would be welcomed.

I guess, as you described a `checkOnlyNames` option might be added. 

After [this line](https://github.com/efkan/content-filter/blob/master/index.js#L104) this new option may be checked by using an `if` conditional expression. If `checkOnlyNames` is true, a new `for..loop` may be started to checking only names. 

Note: Checking the option in present `for..loop` may caused to a performance issue.

**Comment by netpedro-com** [comment]
I found this project [express-mongo-sanitize](https://github.com/fiznool/express-mongo-sanitize) best suited for my project. Right now I'm working in a bug that I found there. Sorry for that. Keep your good work. See ya.

**Comment by efkan** [comment]
I'm glad that you could find a suitable solution.
I wish successful results for your project..
