### ISSUE TITLE
Don't append found Character to message if not wanted

### ISSUE THREAD

**Issue by peanutbother** [efkan/content-filter#8]
The expected behavior would be to offer an option to do this, otherwise don't append a value to a userdefined message. The developer maybe won't expect this behavior and trys to trace it.
This Issue also partly adresses [#6](https://github.com/efkan/content-filter/issues/6).

behaviour found here: 
https://github.com/efkan/content-filter/blob/master/index.js#L46
https://github.com/efkan/content-filter/blob/master/index.js#L48
https://github.com/efkan/content-filter/blob/master/index.js#L81
https://github.com/efkan/content-filter/blob/master/index.js#L83

I will bring in a fork for this issue. please consider this as a feature request / fix.

**Comment by peanutbother** [comment]
Thanks for applying my patch.
Since this patch is now merged and builds are passing successfully, when can we expect to see these changes in NPM registry?

**Comment by efkan** [comment]
It published into NPM right now.

Have a fabulous day!
